document.getElementById("name-1").innerHTML = "Макарон із гороху жовтого";
document.getElementById("name-2").innerHTML = "Макарони із сочевиці зеленої";
document.getElementById("name-3").innerHTML = "Макарони із квасолі";
document.getElementById("name-4").innerHTML = "Макарони із сочевиці червоної";
document.getElementById("name-5").innerHTML = "Макарони з гороху жовтого";
document.getElementById("name-6").innerHTML = "Макарони із сочевиці зеленої";
document.getElementById("name-7").innerHTML = "Макарони з гороху зеленого";
document.getElementById("price.product1").innerHTML = "85 грн";
document.getElementById("price.product2").innerHTML = "85 грн";
document.getElementById("price.product3").innerHTML = "85 грн";
document.getElementById("price.product4").innerHTML = "85 грн";
document.getElementById("price.product5").innerHTML = "85 грн";
document.getElementById("price.product6").innerHTML = "85 грн";
document.getElementById("price.product7").innerHTML = "85 грн";
document.getElementById("avatar-1").innerHTML ='<img src="img/peas.jpg"> <div class="product-type""><img src="img/spiral.png"></div>';
document.getElementById("avatar-2").innerHTML ='<img src="img/green-lentils-spiral.jpg"> <div class="product-type"><img src="img/spiral.png"></div>';
document.getElementById("avatar-3").innerHTML ='<img src="img/bean.jpg"> <div class="product-type"><img src="img/spiral.png"></div>';
document.getElementById("avatar-4").innerHTML ='<img src="img/red-lentils-spiral.jpg"> <div class="product-type"><img src="img/spiral.png"></div>';
document.getElementById("avatar-5").innerHTML ='<img src="img/peas-mushla-yellow.jpg"> <div class="product-type"><img src="img/spiral.png"></div>';
document.getElementById("avatar-6").innerHTML ='<img src="img/green-lentils-mushla.jpg"> <div class="product-type"><img src="img/spiral.png"></div>';document.getElementById("avatar-7").innerHTML ='<img src="img/peas-green-spiral.jpg"> <div class="product-type"><img src="img/spiral.png"></div>';
